# Generated by Django 4.2.2 on 2023-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='picture',
            field=models.ImageField(default='django-proj/static/images/profile.jpeg', upload_to='django-proj/static/images'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
