# Generated by Django 4.2.2 on 2023-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0003_alter_observation_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='picture',
            field=models.ImageField(default='profile.jpeg', upload_to='static/images'),
        ),
    ]
