# Generated by Django 4.1 on 2023-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0006_rename_bird_category_observation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='picture',
            field=models.ImageField(default='profile.jpeg', upload_to=''),
        ),
    ]
